name: Build Release Zip

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Build DeathDirge.zip
        run: |
          ASSET_NAME="ddc-v${{ github.event.release.tag_name }}.zip"
          mkdir -p build/DeathDirge
          rsync -av \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'DeathDirge.zip' \
            ./ build/DeathDirge/
          cd build
          zip -r "$ASSET_NAME" DeathDirge

      - name: Attach zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: build/ddc-v${{ github.event.release.tag_name }}.zip
